# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 08:04
from __future__ import unicode_literals

import apps.utils
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. 64 characters or fewer.', max_length=64, verbose_name='Organization Name')),
                ('avatar', models.ImageField(upload_to=apps.utils.media_folder, verbose_name='Organization Logo')),
                ('owner', models.UUIDField(default=uuid.uuid4, help_text='User uuid, this token will identify who is the owner of respective Organization.', verbose_name='Owner Unique Identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Organization Creation time.')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Organization Modification time.')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': 'Organization',
                'get_latest_by': 'id',
                'verbose_name_plural': 'Organization',
            },
        ),
    ]
