# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 09:20
from __future__ import unicode_literals

import apps.utils
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. 64 characters or fewer.', max_length=64, verbose_name='Organization Name')),
                ('logo', imagekit.models.fields.ProcessedImageField(upload_to=apps.utils.media_folder)),
                ('created_at', models.DateTimeField(db_index=True, verbose_name='Organization Creation time.')),
                ('modified_at', models.DateTimeField(db_index=True, verbose_name='Organization Modification time.')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': 'Organization',
                'get_latest_by': 'id',
                'verbose_name_plural': 'Organization',
            },
        ),
    ]
