# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='owner',
            field=models.UUIDField(help_text='User uuid, this token will identify who is the owner of respective Organization.', verbose_name='Owner Unique Identifier'),
        ),
    ]
