# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170424_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrganization',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('organization.organization',),
        ),
        migrations.AlterField(
            model_name='organization',
            name='avatar',
            field=models.URLField(verbose_name='Organization Logo'),
        ),
    ]
