# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='type',
            field=models.CharField(choices=[('terminal', 'terminal'), ('user', 'user')], help_text='Member type, for internal user only', max_length=8, verbose_name='Member type.'),
        ),
    ]
