# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20170420_1153'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='member',
            name='organization',
        ),
    ]
