# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170424_0632'),
        ('members', '0003_auto_20170424_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='organization',
            field=models.ForeignKey(default='538a7285-bd16-4a4e-8934-852a7b2f6486', help_text='Member Organization.', on_delete=django.db.models.deletion.CASCADE, to='organization.Organization', to_field='token'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([('email', 'organization')]),
        ),
    ]
