# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20170424_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.UUIDField(default='847eb45a-c913-429b-a97a-82ca1a3ebacd', help_text='User uuid, this uid will identify associated User with respective Member.', verbose_name='Member associated User UUID'),
            preserve_default=False,
        ),
    ]
