# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='organization',
            field=models.ForeignKey(help_text='Member Organization.', on_delete=django.db.models.deletion.CASCADE, related_name='organization_members', to='organization.Organization', to_field='token'),
        ),
    ]
