# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_remove_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.CharField(default=1, help_text='User Username, this will identify associated User with respective Member.', max_length=100, verbose_name='Member associated User Username'),
            preserve_default=False,
        ),
    ]
